[package]
name = "esys_wirehair"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"

[build-dependencies]
cmake = "0.1.50"

[dev-dependencies]
rand = "0.8.5"
